name: easy_course
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.40+60

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4
  url_strategy: ^0.3.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.2
  fluttertoast: ^8.2.8
  pinput: ^5.0.0
  flutter_html: ^3.0.0-beta.2
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  flutter_inappwebview: ^6.0.0
  hidable: ^1.0.6
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  flutter_image_compress: ^2.3.0
  mobile_scanner: ^5.2.3
  chucker_flutter: ^1.8.1
  chopper: ^8.0.2
  open_file: ^3.5.6
  sqflite: ^2.4.0
  add_to_cart_animation: ^2.0.4
  esc_pos_utils_plus: ^2.0.4
  flutter_pos_printer_platform_image_3: ^1.2.4
  in_app_update: ^4.2.3
  syncfusion_flutter_charts: ^28.1.36
  in_app_review: ^2.0.9
  facebook_app_events: ^0.19.4
  package_info_plus: ^8.1.1
  record: ^5.2.0
  just_audio: ^0.9.42
  device_info_plus: ^11.2.0
  permission_handler: ^11.3.1
  audio_visualizer: ^1.1.0
  app_links: ^6.3.2
  timeago: ^3.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/language/
    - assets/icon/
    - assets/icon/svg/

  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/font/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/font/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/font/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/InstrumentSans-Bold.ttf
          weight: 700
